# Generated by Django 4.1.4 on 2022-12-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstlogin',
            field=models.BooleanField(default=False),
        ),
    ]
