# Generated by Django 4.1.5 on 2023-01-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_desc',
            new_name='product_dese',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='exit', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(upload_to='product_pic'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
