# Generated by Django 4.1.5 on 2023-02-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_contact_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_user',
        ),
    ]
